# Header
menu:
  首页: /
  归档: /archives

rss: /atom.xml
nav: right
mobile_nav: right



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
# background_image: /images/bg.jpeg
background_title: 图片来自网络

#Userinfo
author: 一路烟霞
slogan: 特别耐撕的小前端，资深的打酱油攻城狮。
# avatar: /images/code-title.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  owner: 
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 
favicon: /images/default-avatar.webp
twitter:
google_plus:
fb_admins:
fb_app_id:
keywords:

